[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:api]
directory=/app/api
command=/app/api/.venv/bin/gunicorn --bind 0.0.0.0:%(ENV_DIFY_PORT)s --workers %(ENV_SERVER_WORKER_AMOUNT)s --worker-class %(ENV_SERVER_WORKER_CLASS)s --worker-connections %(ENV_SERVER_WORKER_CONNECTIONS)s --timeout %(ENV_GUNICORN_TIMEOUT)s app:socketio_app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
directory=/app/api
command=/app/api/.venv/bin/celery -A celery_entrypoint.celery worker -P %(ENV_CELERY_WORKER_CLASS)s -c %(ENV_CELERY_WORKER_AMOUNT)s --max-tasks-per-child %(ENV_MAX_TASKS_PER_CHILD)s --loglevel %(ENV_LOG_LEVEL)s -Q api_token,dataset,dataset_summary,priority_dataset,priority_pipeline,pipeline,mail,ops_trace,app_deletion,plugin,workflow_storage,conversation,workflow,schedule_poller,schedule_executor,triggered_workflow_dispatcher,trigger_refresh_publisher,trigger_refresh_executor,retention,workflow_based_app_execution --prefetch-multiplier=%(ENV_CELERY_PREFETCH_MULTIPLIER)s
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
